#:schema node_modules/wrangler/config-schema.json
name = "trivia-jam"
compatibility_date = "2025-12-01"

kv_namespaces = [
  { binding = "KV_STORAGE", id = "7ca58075ccd54315b82982f3c8d0e32d" }
]

[vars]
ACTOR_KIT_HOST = "triviajam.tv"

[[durable_objects.bindings]]
name = "SESSION"
class_name = "Session"

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Remix", "Session", "Game"]

[[migrations]]
tag = "v2"
deleted_classes = ["Remix"]

[observability]
enabled = true
